# Link to video.

### Raising Errors

We've seen a variety of error messages that appear when our programs end abruptly. We can create our own errors messages too.

```python
def add_integers(*nums):
    """Takes an unlimited number of integers and returns their sum."""
    try:
        total = 0
        for num in nums:
            total += num
        return num
    except:
        raise TypeError("All arguments must be integers")

print(add_integers(3, -4, 2, 7))  # prints 8
print(add_integers("hi"))  # prints a red error message saying "TypeError: All arguments must be integers"
```

The keyword `raise` is used to raise an error. We can use any of [the built-in errors](https://docs.python.org/3/library/exceptions.html).

If we `raise` within an `except` block, we'll get both the original error as well as the new error. We can avoid getting the first one by using a boolean variable to keep track of whether we need to raise it

```python
def add_integers(*nums):
    """Takes an unlimited number of integers and returns their sum."""
    error = False
    try:
        total = 0
        for num in nums:
            total += num
        return total
    except:
        error = True
    if error:
        raise TypeError("All arguments must be integers")

print(add_integers("hi"))  # prints a red error message saying "TypeError: All arguments must be integers."
```  

We can also create our own custom error types, which we'll do later this unit.
